// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gotoc.proto

package gotocpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//命令类型
type CmdID int32

const (
	CmdID_ADD_REQ CmdID = 0
	CmdID_ADD_RSP CmdID = 1
)

var CmdID_name = map[int32]string{
	0: "ADD_REQ",
	1: "ADD_RSP",
}

var CmdID_value = map[string]int32{
	"ADD_REQ": 0,
	"ADD_RSP": 1,
}

func (x CmdID) String() string {
	return proto.EnumName(CmdID_name, int32(x))
}

func (CmdID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f0bc86029d1e7f8f, []int{0}
}

//消息体
type MsgBody struct {
	ID                   CmdID    `protobuf:"varint,1,opt,name=ID,proto3,enum=gotocpb.CmdID" json:"ID,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBody) Reset()         { *m = MsgBody{} }
func (m *MsgBody) String() string { return proto.CompactTextString(m) }
func (*MsgBody) ProtoMessage()    {}
func (*MsgBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0bc86029d1e7f8f, []int{0}
}

func (m *MsgBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBody.Unmarshal(m, b)
}
func (m *MsgBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBody.Marshal(b, m, deterministic)
}
func (m *MsgBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBody.Merge(m, src)
}
func (m *MsgBody) XXX_Size() int {
	return xxx_messageInfo_MsgBody.Size(m)
}
func (m *MsgBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBody.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBody proto.InternalMessageInfo

func (m *MsgBody) GetID() CmdID {
	if m != nil {
		return m.ID
	}
	return CmdID_ADD_REQ
}

func (m *MsgBody) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddReq struct {
	Num1                 int32    `protobuf:"fixed32,1,opt,name=Num1,proto3" json:"Num1,omitempty"`
	Num2                 int32    `protobuf:"fixed32,2,opt,name=Num2,proto3" json:"Num2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReq) Reset()         { *m = AddReq{} }
func (m *AddReq) String() string { return proto.CompactTextString(m) }
func (*AddReq) ProtoMessage()    {}
func (*AddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0bc86029d1e7f8f, []int{1}
}

func (m *AddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReq.Unmarshal(m, b)
}
func (m *AddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReq.Marshal(b, m, deterministic)
}
func (m *AddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReq.Merge(m, src)
}
func (m *AddReq) XXX_Size() int {
	return xxx_messageInfo_AddReq.Size(m)
}
func (m *AddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddReq proto.InternalMessageInfo

func (m *AddReq) GetNum1() int32 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *AddReq) GetNum2() int32 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type AddRsp struct {
	Sum                  int32    `protobuf:"fixed32,1,opt,name=Sum,proto3" json:"Sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRsp) Reset()         { *m = AddRsp{} }
func (m *AddRsp) String() string { return proto.CompactTextString(m) }
func (*AddRsp) ProtoMessage()    {}
func (*AddRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0bc86029d1e7f8f, []int{2}
}

func (m *AddRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRsp.Unmarshal(m, b)
}
func (m *AddRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRsp.Marshal(b, m, deterministic)
}
func (m *AddRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRsp.Merge(m, src)
}
func (m *AddRsp) XXX_Size() int {
	return xxx_messageInfo_AddRsp.Size(m)
}
func (m *AddRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddRsp proto.InternalMessageInfo

func (m *AddRsp) GetSum() int32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto.RegisterEnum("gotocpb.CmdID", CmdID_name, CmdID_value)
	proto.RegisterType((*MsgBody)(nil), "gotocpb.MsgBody")
	proto.RegisterType((*AddReq)(nil), "gotocpb.AddReq")
	proto.RegisterType((*AddRsp)(nil), "gotocpb.AddRsp")
}

func init() { proto.RegisterFile("gotoc.proto", fileDescriptor_f0bc86029d1e7f8f) }

var fileDescriptor_f0bc86029d1e7f8f = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcf, 0x2f, 0xc9,
	0x4f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0x73, 0x0a, 0x92, 0x94, 0x6c, 0xb9,
	0xd8, 0x7d, 0x8b, 0xd3, 0x9d, 0xf2, 0x53, 0x2a, 0x85, 0xe4, 0xb8, 0x98, 0x3c, 0x5d, 0x24, 0x18,
	0x15, 0x18, 0x35, 0xf8, 0x8c, 0xf8, 0xf4, 0xa0, 0x0a, 0xf4, 0x9c, 0x73, 0x53, 0x3c, 0x5d, 0x82,
	0x98, 0x3c, 0x5d, 0x84, 0x84, 0xb8, 0x58, 0x5c, 0x12, 0x4b, 0x12, 0x25, 0x98, 0x14, 0x18, 0x35,
	0x78, 0x82, 0xc0, 0x6c, 0x25, 0x03, 0x2e, 0x36, 0xc7, 0x94, 0x94, 0xa0, 0xd4, 0x42, 0x90, 0xac,
	0x5f, 0x69, 0xae, 0x21, 0x58, 0x3f, 0x7f, 0x10, 0x98, 0x0d, 0x15, 0x33, 0x02, 0xeb, 0x80, 0x88,
	0x19, 0x29, 0x49, 0x41, 0x74, 0x14, 0x17, 0x08, 0x09, 0x70, 0x31, 0x07, 0x97, 0xe6, 0x42, 0x35,
	0x80, 0x98, 0x5a, 0x8a, 0x5c, 0xac, 0x60, 0xeb, 0x84, 0xb8, 0xb9, 0xd8, 0x1d, 0x5d, 0x5c, 0xe2,
	0x83, 0x5c, 0x03, 0x05, 0x18, 0xe0, 0x9c, 0xe0, 0x00, 0x01, 0xc6, 0x24, 0x36, 0xb0, 0xfb, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x46, 0xd3, 0xd1, 0xc9, 0xce, 0x00, 0x00, 0x00,
}
